### ISSUE TITLE
merch cards

### ISSUE THREAD

**Issue by christopherjohnson1** [nss-evening-cohort-11/bands-viking-galaxy#10]
## User Story
As a user, you should see a store full of band merch

## AC
WHEN the page loads
THEN you should see rows of merchandise cards with 4 cards per row
AND each card should have an image of the merch item, item name, price, and availability

## Dev Notes
* In merch.html, add a div with id='merch' with a class of `"d-flex flex-wrap"`
* create an array called vikingMerch in main.js with a bunch (6) of merch objects
* Create a merchBuilder function - that takes in an array, loops over the array, builds a domString (`<img>`, `<h2>` tags for merch item name, and `<p>` tags for price and availability. Merch container should have a class of col-3) and calls printToDom
* reference merch availability form for building notifier form for unavailable items
* add merch mockups to the assets directory

**Comment by John-Fleming** [comment]
![Screen Shot 2020-02-04 at 8 23 56 PM](https://user-images.githubusercontent.com/51543096/73902275-e08fd300-485a-11ea-8097-15b73b9c91c8.png)
