### ISSUE TITLE
purchase tickets button

### ISSUE THREAD

**Issue by christopherjohnson1** [nss-evening-cohort-11/bands-viking-galaxy#11]
## User Story
As a user, I should click a button to purchase tickets 

## AC
WHEN I navigate to the tour page
THEN I should see the table with all concerts, dates, and venues
AND the last column should should have a button in each row that displays `Tickets`
AND when I click the button, a window alert will pop up and say "Congrats! Your tickets have been purchased!"

## Dev Notes
* In main.js, add a event listener that targets the id of the button in the `concertBuilder` function
* when the event listener is called, it should call a function called `purchaseTickets` that will `alert()` with a message that says "Congrats! Your tickets have been purchased!"
* reference Advanced tickets button ticket for stretch goal button functionality

**Comment by John-Fleming** [comment]
![Screen Shot 2020-02-10 at 7 00 41 PM](https://user-images.githubusercontent.com/51543096/74204155-a7c77380-4c37-11ea-98c4-fae991477a1a.png)

**Comment by StevenZelenak** [comment]
```js
//function that creates tickets id's (was not in card to create)
const ticketIdCreator = () => {
    for (let i = 0; i < concerts.length; i++) {
        concerts[i].Id = i.toString();
    }
    return concerts;
}
```
Had to create a function to give all the Buttons their own Id.
