### ISSUE TITLE
discography cards

### ISSUE THREAD

**Issue by John-Fleming** [nss-evening-cohort-11/bands-viking-galaxy#13]
## User Story
As a user, you should be able to view details about each of the band's albums in a carousel

## AC
WHEN the page loads
THEN you should see 1 card displayed in the viewport
AND controls on either side will let you switch between albums
AND each card should display an image of the album, the name of the album, the year it was released, and a tracklist in two columns 

## Dev Notes
* In discography.html, add a div with id='albums' and a class="container"
* create an array called discography  in main.js with a bunch (4) of album objects
* Create a albumBuilder function - that takes in an array, loops over the array, builds a domString containing bootstrap carousel code (divs with carousel classes, `<img>`, `<h2>` tags for album name, `<p>` tag for year, and `<ol>` for tracks), and calls printToDom - https://getbootstrap.com/docs/4.0/components/carousel/
* to add the tracklist, you have to access the array index value of the tracklist when accessing the tracklist key from the discography object. The template literal will like like this - `${arr[i].tracklist[0]}`

**Comment by John-Fleming** [comment]
```js
// example array with example object
const discography = [
{
albumArt: "imgURL",
albumName: "Viking Galaxy Greatest Hits",
yearReleased: 1994,
tracklist: [1. blah blah, 2. blah blah blah....]
}
];
```

**Comment by John-Fleming** [comment]
![Screen Shot 2020-02-04 at 8 10 33 PM](https://user-images.githubusercontent.com/51543096/73900556-c0114a00-4855-11ea-8f55-46055e6024cd.png)

**Comment by zoeames** [comment]
how are you going to handle the tracks?

**Comment by John-Fleming** [comment]
Decided to switch the stacking order of the album artwork and the album name and release year
