### ISSUE TITLE
main.js function setup (printToDom, events, init)

### ISSUE THREAD

**Issue by John-Fleming** [nss-evening-cohort-11/bands-viking-galaxy#15]
## User Story
As a developer, you should see JS functions created

## AC
WHEN you look at this card
THEN you will see a js function written for printToDom
AND a js function written for events
AND a js function written for init

##  Dev Notes
* Create a printToDom function that that takes in `divId` and `textToPrint` as parameters
* create an events function that is empty and will hold future event listeners
* create a init function that will hold all functions required on page load

**Comment by John-Fleming** [comment]
printToDom function
```js
const printToDom = (divId, textToPrint) => {
    let selectedDiv = document.getElementById(divId);
    selectedDiv.innerHTML = textToPrint;
};
```

**Comment by zoeames** [comment]
there is nothing deliverable to the user here.  These functions should get folded into other tickets as they are needed
