### ISSUE TITLE
finalize site styles

### ISSUE THREAD

**Issue by John-Fleming** [nss-evening-cohort-11/bands-viking-galaxy#16]
## User Story
As a developer, you should refactor code for consistent styles across site

## AC
WHEN navigating through each page on the site
THEN you should see consistent fonts, colors, and card and button styles
AND it will look awesome

## Dev Notes
* add comments to this ticket for any CSS and Bootstrap style changes that have to be made

**Comment by ToddSpainhour** [comment]
About Page Styling Changes
-make band member images same size with max-height
-make band member images round with border-radius
-squeeze history text away from page edge
-center headings
