### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by John-Fleming** [nss-evening-cohort-11/bands-viking-galaxy#4]
## User Story
As a user, at the bottom of every page, there should be a footer that shows me copyright details

## AC
WHEN the page loads
THEN I should see a footer at the bottom
AND it should have `copyright 2020 Viking Galaxy` displayed in the center of every page

## Dev Notes
* Add a `<footer>` container to the html body with a bootstrap `.text-center` class to center the text on the page
* add a link to access font awesome icons in the header of the each html file - `<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">`
* Add a p tag containing 2020 Viking Galaxy within the footer tag on every html page
* Add a font awesome copyright icon tag within the p tag containing 2020 Viking Galaxy so that the icon displays before the text and add that to every html page - https://fontawesome.com/icons/copyright?style=solid

**Comment by StevenZelenak** [comment]
Added a Bootstrap `fix-bottom` to the footer class to make the footer sit at the bottom.

[https://v4-alpha.getbootstrap.com/utilities/position/](url)
