### ISSUE TITLE
tour date containers/rows

### ISSUE THREAD

**Issue by christopherjohnson1** [nss-evening-cohort-11/bands-viking-galaxy#9]
## User Story
As a user, you should see all upcoming concerts for the band in a table

## AC
WHEN the page loads
THEN you should see a table with four headers - date, venue, location, and tickets
AND below the headers you will see all the upcoming concerts on the band's schedule

## Dev Notes
* In tour.html, add a bootstrap table that contains the `<thead>` elements hardcoded in to include date, venue, location, and tickets as `<th>` elements, and give the `<tbody>` an id of `#tour-info` - https://getbootstrap.com/docs/4.0/content/tables/
* create an array called concerts in main.js with a bunch (20) of concert objects
* Create a concertBuilder function - that takes in an array, loops over the array, builds a domString (containing `<tr>` tags with child elements of `<th>` and separate `<td>` tags for each array object key value pairs) and calls printToDom
* reference purchase tickets button ticket for functionality adding a button to the tickets column of the concerts table

**Comment by christopherjohnson1** [comment]
![image](https://user-images.githubusercontent.com/58916138/73900701-30b86680-4856-11ea-8575-90a152f53ac4.png)

**Comment by christopherjohnson1** [comment]
![image](https://user-images.githubusercontent.com/58916138/73900737-4fb6f880-4856-11ea-80a7-6a9cf6349eae.png)

**Comment by zoeames** [comment]
what happens when the purchase button is clicked?
